[package]
name = "mini-motorways"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Sycrosity <72102935+Sycrosity@users.noreply.github.com>"]

[dependencies]
bevy = "0.16.1"
